# Generated by Django 2.1.7 on 2019-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tpoic_name',
            new_name='topic_name',
        ),
    ]
